# Generated by Django 5.1.7 on 2025-11-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='extra_data',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_certificate',
            field=models.FileField(blank=True, null=True, upload_to='profiles/certificates/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.FileField(blank=True, null=True, upload_to='profiles/national_ids/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='profiles/passports/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/passport_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification_level',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
