# Generated by Django 5.1.7 on 2025-11-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_extra_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=255)),
                ('knqf_level', models.CharField(max_length=50)),
                ('academic_certificate', models.FileField(upload_to='applications/certificates/')),
                ('passport_photo', models.ImageField(upload_to='applications/photos/')),
                ('national_id', models.FileField(blank=True, null=True, upload_to='applications/ids/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='applications/passports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
