# Generated by Django 4.2.26 on 2025-11-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentApplication',
        ),
    ]
