# Generated by Django 4.2.26 on 2025-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_create_courses_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
