# Generated by Django 4.2.26 on 2025-12-30 16:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='notifications',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Messages or notifications for this section'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='storage',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Uploaded documents or file references'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
