# Generated by Django 4.2.26 on 2025-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='assignments',
            field=models.TextField(blank=True, help_text='Assignment details or references'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='notifications',
            field=models.TextField(blank=True, help_text='Messages or notifications for this section'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='quizzes',
            field=models.TextField(blank=True, help_text='Quiz details or references'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='resources',
            field=models.TextField(blank=True, help_text='Links, PDFs, or other resources'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='storage',
            field=models.TextField(blank=True, help_text='Uploaded documents or file references'),
        ),
        migrations.DeleteModel(
            name='CourseModule',
        ),
    ]
