# Generated by Django 4.2.26 on 2025-11-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_attachment_assignment_attachments'),
        ('courses', '0006_coursesection_assignments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresource',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='resources', to='assignments.attachment'),
        ),
    ]
