# Generated by Django 4.2.26 on 2025-11-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_remove_assignmentgrade_grader_and_more'),
        ('courses', '0007_courseresource_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='resources',
        ),
        migrations.DeleteModel(
            name='CourseResource',
        ),
        migrations.AddField(
            model_name='coursesection',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='section_assignments', to='assignments.attachment'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='section_quizzes', to='assignments.attachment'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='section_resources', to='assignments.attachment'),
        ),
    ]
