# Generated by Django 4.2.26 on 2026-01-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_scormpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormpackage',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scorm_packages', to='courses.coursesection'),
            preserve_default=False,
        ),
    ]
