# Generated by Django 4.2.26 on 2025-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_remove_assignmentgrade_grader_and_more'),
        ('courses', '0008_remove_coursesection_assignments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='resource_attachments', to='assignments.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='quiz_attachments', to='assignments.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='assignment_attachments', to='assignments.attachment')),
            ],
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='section_assignments', to='courses.assignment'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='section_quizzes', to='courses.quiz'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='section_resources', to='courses.resource'),
        ),
    ]
