# Generated by Django 4.2.26 on 2025-11-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_resource_quiz_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='attachments',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.coursesection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='course_section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.coursesection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='course_section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.coursesection'),
            preserve_default=False,
        ),
    ]
