# Generated by Django 4.2.26 on 2025-11-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('link', 'Link'), ('text', 'Text')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='assignments.attachment'),
        ),
    ]
