# Generated by Django 4.2.26 on 2025-11-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_attachment_assignment_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentgrade',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='assignmentgrade',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentGrade',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
