# Generated by Django 4.2.26 on 2025-11-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_assignment_attachments_and_more'),
        ('assignments', '0004_remove_assignmentgrade_grader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.quiz'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.resource'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF, video, audio, or other files', null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='text',
            field=models.TextField(blank=True, help_text='Add text content if needed'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('link', 'Link'), ('text', 'Text'), ('video', 'Video'), ('audio', 'Audio')], max_length=10),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(blank=True, help_text='Add a link for web resources, videos, etc.'),
        ),
    ]
